export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

import { createClient } from '@/utils/supabase/server';
import { checkEntitlement, format402Payload } from '@/utils/aiEntitlements';
import { generateWeeklyBriefForUser, getLastCompletedWeekRange } from '@/utils/weeklyBrief';
import { NextRequest, NextResponse } from 'next/server';

type BriefRow = {
  overview: string;
  themes: unknown;
  created_at: string;
  auto_generated: boolean;
};

async function getExistingForWeek(supabase: Awaited<ReturnType<typeof createClient>>, userId: string, weekStartDate: string) {
  const { data } = await supabase
    .from('weekly_briefs')
    .select('overview, themes, created_at, auto_generated')
    .eq('user_id', userId)
    .eq('week_start', weekStartDate)
    .maybeSingle();

  return (data || null) as BriefRow | null;
}

export async function GET() {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const entitlement = await checkEntitlement(supabase, user.id, 'weekly_brief');
  if (!entitlement.allowed) return NextResponse.json(format402Payload(entitlement), { status: 402 });

  const { weekStartDate, weekEndDate, nextEligibleAt } = getLastCompletedWeekRange();
  const existing = await getExistingForWeek(supabase, user.id, weekStartDate);

  return NextResponse.json({
    brief: existing
      ? {
          overview: existing.overview,
          themes: existing.themes,
          createdAt: existing.created_at,
        }
      : null,
    weekStart: weekStartDate,
    weekEnd: weekEndDate,
    autoGenerated: existing?.auto_generated ?? true,
    generatedNow: false,
    canGenerateNew: false,
    nextEligibleAt,
    tooFewIssues: false,
  });
}

export async function POST(_request: NextRequest) {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const entitlement = await checkEntitlement(supabase, user.id, 'weekly_brief');
  if (!entitlement.allowed) return NextResponse.json(format402Payload(entitlement), { status: 402 });

  const { weekStartDate, weekEndDate, nextEligibleAt } = getLastCompletedWeekRange();

  const existing = await getExistingForWeek(supabase, user.id, weekStartDate);
  if (existing) {
    return NextResponse.json(
      {
        error: 'This weekly insight is already generated. A new one unlocks next Monday.',
        nextEligibleAt,
        weekStart: weekStartDate,
        weekEnd: weekEndDate,
      },
      { status: 409 },
    );
  }

  try {
    const result = await generateWeeklyBriefForUser(supabase, user.id, false);
    if (result.skipped) {
      return NextResponse.json(
        { error: 'Need at least 2 issues in last week to generate this insight.', nextEligibleAt },
        { status: 400 },
      );
    }

    const created = await getExistingForWeek(supabase, user.id, weekStartDate);
    if (!created) return NextResponse.json({ error: 'Failed to generate weekly brief' }, { status: 500 });

    return NextResponse.json({
      overview: created.overview,
      themes: created.themes,
      createdAt: created.created_at,
      weekStart: weekStartDate,
      weekEnd: weekEndDate,
      nextEligibleAt,
    });
  } catch (e) {
    const message = e instanceof Error ? e.message : 'Failed to generate weekly brief';
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
